// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7gx4NR2pSZjBSCSG-bNUeFIplr4bsN8A',
    appId: '1:598494681188:web:84948509b2502ed92f2771',
    messagingSenderId: '598494681188',
    projectId: 'project-akhir-d353f',
    authDomain: 'project-akhir-d353f.firebaseapp.com',
    storageBucket: 'project-akhir-d353f.firebasestorage.app',
    measurementId: 'G-4M2PVFZH5W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1b8aDPtmCxxOW_RrMNeFIn8dNiHr_0KM',
    appId: '1:598494681188:android:a1c6ba9338230c7f2f2771',
    messagingSenderId: '598494681188',
    projectId: 'project-akhir-d353f',
    storageBucket: 'project-akhir-d353f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjMcrCVRcFtlycY6g-fX9aD2EaXNaFxfU',
    appId: '1:598494681188:ios:9e9af48bf393490c2f2771',
    messagingSenderId: '598494681188',
    projectId: 'project-akhir-d353f',
    storageBucket: 'project-akhir-d353f.firebasestorage.app',
    iosBundleId: 'com.example.project001',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjMcrCVRcFtlycY6g-fX9aD2EaXNaFxfU',
    appId: '1:598494681188:ios:9e9af48bf393490c2f2771',
    messagingSenderId: '598494681188',
    projectId: 'project-akhir-d353f',
    storageBucket: 'project-akhir-d353f.firebasestorage.app',
    iosBundleId: 'com.example.project001',
  );
}
